groups:
- name: example
  rules:
  - alert: HighRequestLatency
    annotations:
      description: 'High request latency on {{ $labels.instance }}'
      summary: 'The application is experiencing high request latency ({{ $value }}s)'
    expr: |
      histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, instance)) > 0.5
    for: 10m
    labels:
      severity: warning
  - alert: InstanceDown
    annotations:
      description: '{{ $labels.instance }} has been down for more than 10 minutes.'
      summary: 'Instance {{ $labels.instance }} down'
    expr: up == 0
    for: 10m
    labels:
      severity: critical