volumes:
    prometheus_data:
    grafana_data:
    pgdata:

services:
    inventory-app:
        container_name: inventory-app
        hostname: inventory-app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .env:/app/.env
        ports:
            - "${GRPC_PORT}:${GRPC_PORT}"
        depends_on:
            - inventory-db
        networks:
            - default
    inventory-db:
        container_name: inventory-db
        hostname: inventory-db
        image: postgres
        environment:
            POSTGRES_PASSWORD: ${PG_PASSWORD}
            POSTGRES_USER: ${PG_USER}
            POSTGRES_DB: ${PG_DBNAME}
        ports:
            - "${PG_PORT}:${PG_PORT}"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - default
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DBNAME}"]
            interval: 5s
            timeout: 5s
    migrate:
        container_name: inventory-migrate
        image: migrate/migrate
        command: -source file://migrations -database ${PG_MIGRATIONS_URL} up
        volumes:
            - ./migrations:/migrations
        depends_on:
            - inventory-db
    prometheus:
        container_name: inventory-prom
        image: prom/prometheus
        ports:
            - "9090:9090"
        volumes:
            - prometheus_data:/prometheus
            - ./prometheus.yaml:/etc/prometheus/prometheus.yml
            - ./alerts.yaml:/etc/prometheus/alerts.yml
        networks:
            - default
    grafana:
        container_name: inventory-grafana
        image: grafana/grafana
        ports:
            - "3000:3000"
        volumes:
            - grafana_data:/var/lib/grafana
        networks:
            - default
networks:
    default:
        driver: bridge
