global:
  scrape_interval: 2s
  evaluation_interval: 2s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "inventory-app"
    static_configs:
      - targets: ["product-app:50001"] # FIXME Можно ли читать с кфг?